export interface Pcinfo{
    _id?: number,
    number?: number,
    name: string,
    date: string,
    city: string,
    phone: string,
    purchase: number,
    sale: number,
    status: string,
    isConfirmed: boolean,
    cancellationReason?: string,
    orderDetails?: any,
    societeCode: string,
}
